%print(SQNR,SNR,SNDR,SFDR,ENOB)
fprintf('SQNR=  %f        decibel\n',sqnr_db)
fprintf('SNR =  %f        decibel\n',snr_db)
fprintf('SNDR=  %f        decibel\n',sndr_db)
fprintf('SFDR=  %f        decibel\n',sfdr_db)
fprintf('ENOB=  %f         Bit\n',ENOB)